### ISSUE TITLE
[CI] Static analysis PR comment for PR from forks

### ISSUE THREAD

**Issue by totorigolo** [kth-step/HolBA#58]
For security reasons, Travis doesn't expose encrypted environment variables to PR from forks. Because of this we're not able to make comments on PR to report static analysis results (see #52 and #56 ).

I tracked this issue and found that we're not the only ones with the problem. The Angular team (so, Google people) stumbled across this issue as soon as 2014, and there is no solution at the moment (for security reasons). **Link**: https://github.com/travis-ci/travis-ci/issues/1946

A workaround is to simply read the logs for the Static analysis stage, which are quite clean because they are short. A possible fix would be to use static analysis / lint Github apps that I'm sure handle this issue.

**TODO**:
- [ ] Dump grep-cheat results in logs (easy, I have a local WIP).
- [ ] Look for using an other GitHub app to comment on PRs.
- [ ] Alternative: mention it in `CONTRIBUTING.md`.

**Somehow related**:
- [ ] Post failing test list as comment on PR _and commits_.

**Comment by andreaslindner** [comment]
Another idea for the cheat checker: It could help to change the script such that it shows how many new cheats have been introduced and where. This can be added to the current information and it doesn't need to replace the current summary of all cheats in the repository.

**Comment by totorigolo** [comment]
How do you propose to save the current cheats? Would that need manual intervention?

I'm just thinking that we can use `git grep` instead of `grep`, so we can just compare before and after the PR (Travis should give that in env vars).

**Comment by andreaslindner** [comment]
I didn't think about realization yet. But my thought should translate into something you suggested - a comparison of before and after PR.
